export const usersData = [
  {
    id: 1,
    name: "Mark Antony",
    username: "markantony",
    email: "mark.antony@company.biz",
    photo: "images/users/1.jpeg",
    address: {
      street: "John Street",
      suite: "Apt. 516",
      city: "Bangalore",
      zip: "500001",
      geo: { lng: "77.5946E", lat: "12.9716N" },
    },
    phone: "9876543210",
    website: "meetmarkantony.com",
    company: { name: "ABC Company", location: "Bangalore" },
  },
  {
    id: 2,
    name: "Chandrasekar Azad",
    username: "chandrasekara",
    email: "chandrasekar.azad@organization.biz",
    photo: "images/users/2.jpeg",
    address: {
      street: "Nehru Nagar",
      suite: "123 North Lane",
      city: "Mysore",
      zip: "550001",
      geo: { lng: "76.6394E", lat: "12.2958N" },
    },
    phone: "9876533211",
    website: "",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 3,
    name: "Rajeev Singh",
    username: "rajeevsingh",
    email: "rajeevsingh@gmail.com",
    photo: "",
    address: {
      street: "Patan Salai",
      suite: "West Hill Apartments 45",
      city: "Jaipur",
      zip: "302029",
      geo: { lat: "26.9124N", lng: "75.7873E" },
    },
    phone: "7828837723",
    website: "images/users/3.jpeg",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 4,
    name: "Shilpa Tagoor",
    username: "shilpatagoor",
    email: "shilpa.tagoor@company.com",
    photo: "images/users/4.jpeg",
    address: {
      street: "Pos Gardens",
      suite: "Gandhi Road, Apartments 125",
      city: "Pune",
      zip: "411002",
      geo: { lng: "73.8567E", lat: "18.5204N" },
    },
    phone: "7898837723",
    website: "",
    company: { name: "IBBMM Corporation", location: "Nasik" },
  },
  {
    id: 5,
    name: "Aradhana Shri",
    username: "aradhanashri",
    email: "aradhana.shri@company.com",
    photo: "images/users/5.jpeg",
    address: {
      street: "Vikram Sarabhai Street",
      suite: "Ustad Hotel Road, Apartments 525",
      city: "Kochi",
      zip: "682001",
      geo: { lng: "76.2673E", lat: "9.9312N" },
    },
    phone: "6628837713",
    website: "",
    company: { name: "TCSS Technology Solution", location: "Kochi" },
  },
  {
    id: 6,
    name: "Aamil Mohammed",
    username: "aamilmohammed",
    email: "aamil.md@techno.com",
    photo: "images/users/6.jpeg",
    address: {
      street: "Anna Street",
      suite: "Mount Round, Apartments 1525",
      city: "Chennai",
      zip: "600004",
      geo: { lng: "80.2707E", lat: "13.0827N" },
    },
    phone: "9938837713",
    website: "",
    company: { name: "Silicon Technology Solution", location: "Chennai" },
  },
  {
    id: 7,
    name: "Saradha Matthew",
    username: "saradhamatthew",
    email: "saradhamatthew@millka.com",
    photo: "images/users/7.jpeg",
    address: {
      street: "Tagore Road",
      suite: "Victoria Palace, Apartments 510",
      city: "Kolkata",
      zip: "700004",
      geo: { lng: "88.3639E", lat: "22.5726N" },
    },
    phone: "8928312347",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
  {
    id: 8,
    name: "Tony Jacob",
    username: "tonyjacob",
    email: "tonyjacob@millka.com",
    photo: "images/users/8.jpeg",
    address: {
      street: "North East Road",
      suite: "Guwahati Flowers, House 1283",
      city: "Dispur",
      zip: "781005",
      geo: { lng: "91.7898E", lat: "26.1433N" },
    },
    phone: "7837462374",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
  {
    id: 1,
    name: "Mark Antony",
    username: "markantony",
    email: "mark.antony@company.biz",
    photo: "images/users/1.jpeg",
    address: {
      street: "John Street",
      suite: "Apt. 516",
      city: "Bangalore",
      zip: "500001",
      geo: { lng: "77.5946E", lat: "12.9716N" },
    },
    phone: "9876543210",
    website: "meetmarkantony.com",
    company: { name: "ABC Company", location: "Bangalore" },
  },
  {
    id: 2,
    name: "Chandrasekar Azad",
    username: "chandrasekara",
    email: "chandrasekar.azad@organization.biz",
    photo: "images/users/2.jpeg",
    address: {
      street: "Nehru Nagar",
      suite: "123 North Lane",
      city: "Mysore",
      zip: "550001",
      geo: { lng: "76.6394E", lat: "12.2958N" },
    },
    phone: "9876533211",
    website: "",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 3,
    name: "Rajeev Singh",
    username: "rajeevsingh",
    email: "rajeevsingh@gmail.com",
    photo: "",
    address: {
      street: "Patan Salai",
      suite: "West Hill Apartments 45",
      city: "Jaipur",
      zip: "302029",
      geo: { lat: "26.9124N", lng: "75.7873E" },
    },
    phone: "7828837723",
    website: "images/users/3.jpeg",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 4,
    name: "Shilpa Tagoor",
    username: "shilpatagoor",
    email: "shilpa.tagoor@company.com",
    photo: "images/users/4.jpeg",
    address: {
      street: "Pos Gardens",
      suite: "Gandhi Road, Apartments 125",
      city: "Pune",
      zip: "411002",
      geo: { lng: "73.8567E", lat: "18.5204N" },
    },
    phone: "7898837723",
    website: "",
    company: { name: "IBBMM Corporation", location: "Nasik" },
  },
  {
    id: 5,
    name: "Aradhana Shri",
    username: "aradhanashri",
    email: "aradhana.shri@company.com",
    photo: "images/users/5.jpeg",
    address: {
      street: "Vikram Sarabhai Street",
      suite: "Ustad Hotel Road, Apartments 525",
      city: "Kochi",
      zip: "682001",
      geo: { lng: "76.2673E", lat: "9.9312N" },
    },
    phone: "6628837713",
    website: "",
    company: { name: "TCSS Technology Solution", location: "Kochi" },
  },
  {
    id: 6,
    name: "Aamil Mohammed",
    username: "aamilmohammed",
    email: "aamil.md@techno.com",
    photo: "images/users/6.jpeg",
    address: {
      street: "Anna Street",
      suite: "Mount Round, Apartments 1525",
      city: "Chennai",
      zip: "600004",
      geo: { lng: "80.2707E", lat: "13.0827N" },
    },
    phone: "9938837713",
    website: "",
    company: { name: "Silicon Technology Solution", location: "Chennai" },
  },
  {
    id: 7,
    name: "Saradha Matthew",
    username: "saradhamatthew",
    email: "saradhamatthew@millka.com",
    photo: "images/users/7.jpeg",
    address: {
      street: "Tagore Road",
      suite: "Victoria Palace, Apartments 510",
      city: "Kolkata",
      zip: "700004",
      geo: { lng: "88.3639E", lat: "22.5726N" },
    },
    phone: "8928312347",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
  {
    id: 8,
    name: "Tony Jacob",
    username: "tonyjacob",
    email: "tonyjacob@millka.com",
    photo: "images/users/8.jpeg",
    address: {
      street: "North East Road",
      suite: "Guwahati Flowers, House 1283",
      city: "Dispur",
      zip: "781005",
      geo: { lng: "91.7898E", lat: "26.1433N" },
    },
    phone: "7837462374",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
  {
    id: 1,
    name: "Mark Antony",
    username: "markantony",
    email: "mark.antony@company.biz",
    photo: "images/users/1.jpeg",
    address: {
      street: "John Street",
      suite: "Apt. 516",
      city: "Bangalore",
      zip: "500001",
      geo: { lng: "77.5946E", lat: "12.9716N" },
    },
    phone: "9876543210",
    website: "meetmarkantony.com",
    company: { name: "ABC Company", location: "Bangalore" },
  },
  {
    id: 2,
    name: "Chandrasekar Azad",
    username: "chandrasekara",
    email: "chandrasekar.azad@organization.biz",
    photo: "images/users/2.jpeg",
    address: {
      street: "Nehru Nagar",
      suite: "123 North Lane",
      city: "Mysore",
      zip: "550001",
      geo: { lng: "76.6394E", lat: "12.2958N" },
    },
    phone: "9876533211",
    website: "",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 3,
    name: "Rajeev Singh",
    username: "rajeevsingh",
    email: "rajeevsingh@gmail.com",
    photo: "",
    address: {
      street: "Patan Salai",
      suite: "West Hill Apartments 45",
      city: "Jaipur",
      zip: "302029",
      geo: { lat: "26.9124N", lng: "75.7873E" },
    },
    phone: "7828837723",
    website: "images/users/3.jpeg",
    company: { name: "XYZ Corporation", location: "Mumbai" },
  },
  {
    id: 4,
    name: "Shilpa Tagoor",
    username: "shilpatagoor",
    email: "shilpa.tagoor@company.com",
    photo: "images/users/4.jpeg",
    address: {
      street: "Pos Gardens",
      suite: "Gandhi Road, Apartments 125",
      city: "Pune",
      zip: "411002",
      geo: { lng: "73.8567E", lat: "18.5204N" },
    },
    phone: "7898837723",
    website: "",
    company: { name: "IBBMM Corporation", location: "Nasik" },
  },
  {
    id: 5,
    name: "Aradhana Shri",
    username: "aradhanashri",
    email: "aradhana.shri@company.com",
    photo: "images/users/5.jpeg",
    address: {
      street: "Vikram Sarabhai Street",
      suite: "Ustad Hotel Road, Apartments 525",
      city: "Kochi",
      zip: "682001",
      geo: { lng: "76.2673E", lat: "9.9312N" },
    },
    phone: "6628837713",
    website: "",
    company: { name: "TCSS Technology Solution", location: "Kochi" },
  },
  {
    id: 6,
    name: "Aamil Mohammed",
    username: "aamilmohammed",
    email: "aamil.md@techno.com",
    photo: "images/users/6.jpeg",
    address: {
      street: "Anna Street",
      suite: "Mount Round, Apartments 1525",
      city: "Chennai",
      zip: "600004",
      geo: { lng: "80.2707E", lat: "13.0827N" },
    },
    phone: "9938837713",
    website: "",
    company: { name: "Silicon Technology Solution", location: "Chennai" },
  },
  {
    id: 7,
    name: "Saradha Matthew",
    username: "saradhamatthew",
    email: "saradhamatthew@millka.com",
    photo: "images/users/7.jpeg",
    address: {
      street: "Tagore Road",
      suite: "Victoria Palace, Apartments 510",
      city: "Kolkata",
      zip: "700004",
      geo: { lng: "88.3639E", lat: "22.5726N" },
    },
    phone: "8928312347",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
  {
    id: 8,
    name: "Tony Jacob",
    username: "tonyjacob",
    email: "tonyjacob@millka.com",
    photo: "images/users/8.jpeg",
    address: {
      street: "North East Road",
      suite: "Guwahati Flowers, House 1283",
      city: "Dispur",
      zip: "781005",
      geo: { lng: "91.7898E", lat: "26.1433N" },
    },
    phone: "7837462374",
    website: "millkairon.com",
    company: { name: "Millka Iron Steel Industries", location: "Kolkata" },
  },
];
